CREATE EXTENSION IF NOT EXISTS citext;

DROP TABLE IF EXISTS "users";
DROP TABLE IF EXISTS forums;
DROP TABLE IF EXISTS threads;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS votes;
DROP TABLE IF EXISTS users_forums;

CREATE TABLE "users" (
  nickname CITEXT NOT NULL UNIQUE,
  email CITEXT NOT NULL UNIQUE,
  fullname TEXT NOT NULL,
  about TEXT NOT NULL
);

CREATE TABLE forums (
  slug CITEXT NOT NULL PRIMARY KEY UNIQUE,
  "user" CITEXT NOT NULL,
  title CITEXT  NOT NULL,
  posts INT NOT NULL DEFAULT 0,
  threads INT NOT NULL DEFAULT 0
);

CREATE TABLE threads (
  id SERIAL PRIMARY KEY,
  slug CITEXT DEFAULT NULL UNIQUE,
  author CITEXT NOT NULL,
  created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  forum CITEXT NOT NULL,
  message TEXT NOT NULL,
  title TEXT NOT NULL,
  votes INT DEFAULT 0
);

CREATE TABLE posts (
  id SERIAL PRIMARY KEY,
  parent INT NOT NULL DEFAULT 0,
  author CITEXT NOT NULL,
  created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  forum CITEXT NOT NULL,
  "isEdited" BOOLEAN NOT NULL DEFAULT FALSE,
  message TEXT NOT NULL,
  thread INT NOT NULL,
  path INTEGER[]
);

CREATE TABLE votes (
  "user" CITEXT NOT NULL,
  thread INT NOT NULL,
  voice INT NOT NULL DEFAULT 0
);

CREATE TABLE users_forums (
  "user" CITEXT NOT NULL,
  forum CITEXT NOT NULL
);